apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "domain-exporter.fullname" . }}
  labels:
    {{- include "domain-exporter.labels" . | nindent 4 }}
data:
  domains.yaml: |
    domains:
{{- if .Values.domains }}
{{ .Values.domains | toYaml | indent 6 }}
{{- else }}
      []
{{- end }}
